# Generated by Django 5.0.6 on 2024-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
