# Generated by Django 5.0.6 on 2024-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='book',
            field=models.ManyToManyField(null=True, related_name='tags', to='bookreview.book'),
        ),
    ]
