# Generated by Django 5.0.6 on 2024-10-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0010_remove_tag_book_book_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_date']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='is_public',
        ),
    ]
