# Generated by Django 5.0.6 on 2024-10-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0011_alter_profile_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
