# Generated by Django 5.0.6 on 2024-10-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0012_alter_collection_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
