# Generated by Django 5.0.6 on 2024-10-10 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0013_delete_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
