# Generated by Django 5.0.6 on 2025-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0014_book_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
