# Generated by Django 5.0.6 on 2025-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0015_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/images/author.jpg', upload_to='users/images'),
        ),
    ]
